<a href="https://colab.research.google.com/github/FMML20220102-PervezShaik/Weekly-Assignments/blob/main/Copy_of_FMML_CLF1_Lab3_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FOUNDATIONS OF MODERN MACHINE LEARNING, IIIT Hyderabad**
### MODULE: CLASSIFICATION-1
### LAB-3 : Using KNN for Text Classification
#### Module Coordinator: Tanvi Kamble


---

## **Section 1: Understanding NLP tools** 

In this lab we will be using KNN on a real world NLP application i.e. is text classification. But first look at some NLP techniques for text classification and tools that we use when we want to use python for NLP.

## Section 1.2: Data Cleaning and Preprocessing step

Raw text must be processed and converted into a form so that it is suitable to use with various machine-learning algorithms.  
In case of text, there are lots of things that need to be taken into account.  


1.   Removing numbers from the text
2.   Handling capitalization and punctuation.
3.   Stemming and Lemmatizing text.  

And most importantly, one can't just use words or images directly in algorithms; they need to be converted into vectors- a form that algorithms can understand.



### **NLTK** 
NLTK (or Natural Language Tool Kit) is a commonly used library for processing text. We will use this tool in this lab. Lets first install it. 


In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
import re
import numpy
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import wordnet
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from bs4 import BeautifulSoup

def cleanText(text, lemmatize, stemmer):
    """Method for cleaning text from train and test data. Removes numbers, punctuation, and capitalization. Stems or lemmatizes text."""

    if isinstance(text, float):
        text = str(text)
    if isinstance(text, numpy.int64):
        text = str(text)
    try:
        text = text.decode()
    except AttributeError:
        pass

    soup = BeautifulSoup(text, "lxml")
    text = soup.get_text()
    text = re.sub(r"[^A-Za-z]", " ", text)
    text = text.lower()


    if lemmatize:
        wordnet_lemmatizer = WordNetLemmatizer()

        def get_tag(tag):
            if tag.startswith('J'):
                return wordnet.ADJ
            elif tag.startswith('V'):
                return wordnet.VERB
            elif tag.startswith('N'):
                return wordnet.NOUN
            elif tag.startswith('R'):
                return wordnet.ADV
            else:
                return ''

        text_result = []
        tokens = word_tokenize(text)  # Generate list of tokens
        tagged = pos_tag(tokens)
        for t in tagged:
            try:
                text_result.append(wordnet_lemmatizer.lemmatize(t[0], get_tag(t[1][:2])))
            except:
                text_result.append(wordnet_lemmatizer.lemmatize(t[0]))
        return text_result

    if stemmer:
        text_result = []
        tokens = word_tokenize(text)
        snowball_stemmer = SnowballStemmer('english')
        for t in tokens:
            text_result.append(snowball_stemmer.stem(t))
        return text_result

In [ ]:
sample_text = "Troubling"
sample_text_result = cleanText(sample_text, lemmatize=False, stemmer=True)
sample_text_result = " ".join(str(x) for x in sample_text_result)
print(sample_text)
print(sample_text_result)
sample_text_result = cleanText(sample_text, lemmatize=True, stemmer=False)
sample_text_result = " ".join(str(x) for x in sample_text_result)
print(sample_text_result)

Troubling
troubl
trouble


## Section 1.2: BAG OF WORDS 

A bag-of-words model, or BoW for short, is a way of extracting features from text for use in modeling, such as with machine learning algorithms.

The approach is very simple and flexible, and can be used in many ways for extracting features from documents.

A bag-of-words is a representation of text that describes the occurrence of words within a document. 
It is called a “bag” of words, because any information about the order or structure of words in the document is discarded. The model is only concerned with whether known words occur in the document, not where in the document.

In [ ]:
# Functions to convert document(s) to a list of words, with the option of removing stopwords. Returns document-term matrix.

def createBagOfWords(train, test, remove_stopwords, lemmatize, stemmer):
    if remove_stopwords:
        vectorizer = CountVectorizer(analyzer='word', input='content', stop_words=stopwords.words('english'))
    else:
        vectorizer = CountVectorizer(analyzer='word', input='content')

    clean_train = []
    for paragraph in train:
        paragraph_result = cleanText(paragraph, lemmatize, stemmer)
        paragraph = " ".join(str(x) for x in paragraph_result)
        clean_train.append(paragraph)

    clean_test = []
    for paragraph in test:
        paragraph_result = cleanText(paragraph, lemmatize, stemmer)
        paragraph = " ".join(str(x) for x in paragraph_result)
        clean_test.append(paragraph)

    bag_of_words_train = vectorizer.fit_transform(clean_train).toarray()
    bag_of_words_test = vectorizer.transform(clean_test).toarray()
    return bag_of_words_train, bag_of_words_test


## Section 1.3: TF-IDF 
TF-IDF technique is used to find meaning of sentences consisting of words and cancels out the incapabilities of Bag of Words technique which is good for text classification or for helping a machine read words in numbers.

The number of times a term occurs in a document is called its Term frequency (TF).

 Document frequency is the number of documents in which the word is present.  Inverse DF (IDF) is the inverse of the document frequency which measures the informativeness of term *t*. 




In [ ]:
def createTFIDF(train, test, remove_stopwords, lemmatize, stemmer):
    if remove_stopwords:
        vectorizer = TfidfVectorizer(analyzer='word', input='content', stop_words=stopwords.words('english'))
    else:
        vectorizer =  TfidfVectorizer(analyzer='word', input='content')

    clean_train = []
    for paragraph in train:
        paragraph_result = cleanText(paragraph, lemmatize, stemmer)
        paragraph = " ".join(str(x) for x in paragraph_result)
        clean_train.append(paragraph)

    clean_test = []
    for paragraph in test:
        paragraph_result = cleanText(paragraph, lemmatize, stemmer)
        paragraph = " ".join(str(x) for x in paragraph_result)
        clean_test.append(paragraph)

    tfidf_train = vectorizer.fit_transform(clean_train).toarray()
    tfidf_test = vectorizer.transform(clean_test).toarray()
    return tfidf_train, tfidf_test

# **Section 2: UNDERSTANDING THE DATA : A REVIEWS DATASET**

Sentiment analysis is the interpretation and classification of emotions (such as positive, negative and neutral) within text data using text analysis techniques.  
Given below is a dataset consisting of reviews along with sentiment class (positive or negative).

In [ ]:
# Upload the Reviews CSV file that has been shared with you.
# Run this cell, click on the 'Choose files' button and upload the file.
from google.colab import files
uploaded = files.upload()

Saving reviews.csv to reviews.csv


In [ ]:
import pandas as pd
df = pd.read_csv('reviews.csv')

In [ ]:
df = df.dropna()

In [ ]:
df.count()

sentence     955
sentiment    955
dtype: int64

In [ ]:
df.to_csv('reviews.csv', index=False)

# **Section 3: KNN MODEL**

Given below are two KNN models; in the first case we are using Bag-of-Words and in the second case we are using TF-IDF.
Note the different metrics and parameters used in each.

In [ ]:
from sklearn import metrics, neighbors
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict

## TASK - 1: Tweak the models below and see results with different parameters and distance metrics.

def bow_knn(metric_type,no_of_neighbors,weight):
    """Method for determining nearest neighbors using bag-of-words and K-Nearest Neighbor algorithm"""

    training_data = pd.read_csv('reviews.csv')
    X_train, X_test, y_train, y_test = train_test_split(training_data["sentence"], training_data["sentiment"], test_size=0.2, random_state=5)
    X_train, X_test = createBagOfWords(X_train, X_test, remove_stopwords=True, lemmatize=True, stemmer=False)
    # print(X_train)
    
    knn = neighbors.KNeighborsClassifier(n_neighbors=no_of_neighbors, weights=weight, algorithm='auto', leaf_size=30, p=2, metric=metric_type, metric_params=None, n_jobs=1)

    knn.fit(X_train, y_train)
    predicted = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, predicted)
    
    print(str(metric_type)+' metric, with '+str(no_of_neighbors)+'neighbors and '+str(weight)+' weighted for Bag of words : ')
    print('KNN with BOW accuracy = ' + str(acc * 100) + '% ')

    scores = cross_val_score(knn, X_train, y_train, cv=3)
    print("Cross Validation Accuracy: %0.2f" % (scores.mean()))
    print(scores)
    print('\n')
    return predicted, y_test


def tfidf_knn(metric_type,no_of_neighbors,weight):
    """Method for determining nearest neighbors using tf-idf and K-Nearest Neighbor algorithm"""

    training_data = pd.read_csv('reviews.csv')
    X_train, X_test, y_train, y_test = train_test_split(training_data["sentence"], training_data["sentiment"],
                                                        test_size=0.2, random_state=5)
    X_train, X_test = createTFIDF(X_train, X_test, remove_stopwords=True, lemmatize=True, stemmer=False)
    # print(X_train)
    knn = neighbors.KNeighborsClassifier(n_neighbors=no_of_neighbors, weights=weight, algorithm='brute', leaf_size=30, p=2,
                                         metric=metric_type, metric_params=None, n_jobs=1)

    knn.fit(X_train, y_train)
    predicted = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, predicted)
    
    print(str(metric_type)+' metric, with '+str(no_of_neighbors)+'neighbors and '+str(weight)+' weighted for TF-IDF : ')
    print('KNN with TFIDF accuracy = ' + str(acc * 100) + '%')

    scores = cross_val_score(knn, X_train, y_train, cv=3)
    print("Cross Validation Accuracy: %0.2f" % (scores.mean()))
    print(scores)
    return predicted, y_test

Note: Cross-validation will be discussed in detail in the upcoming lab session.

In [ ]:
#We iterate the algorith for different metrics,no of neighbors and weights type
#Bag of words
metrics_list=['euclidean','manhattan','cosine','chebyshev']
neighbors_list=[3,7,13]
weight_type=['uniform','distance']
for weight in weight_type:
  for metric_type in metrics_list:
    for no_of_neighbors in neighbors_list:
      predicted,y_test=bow_knn(metric_type,no_of_neighbors,weight)  

#TF-IDF
for weight in weight_type:
  for metric_type in metrics_list:
    for no_of_neighbors in neighbors_list:
      predicted,y_test=tfidf_knn(metric_type,no_of_neighbors,weight)  



euclidean metric, with 3neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 62.82722513089005% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.60
[0.61176471 0.59215686 0.59055118]


euclidean metric, with 7neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 64.3979057591623% 
Cross Validation Accuracy: 0.62
[0.60784314 0.58823529 0.67322835]




/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


euclidean metric, with 13neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 57.59162303664922% 
Cross Validation Accuracy: 0.61
[0.58039216 0.62352941 0.63385827]




/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


manhattan metric, with 3neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 61.25654450261781% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.60
[0.60784314 0.59215686 0.59055118]


manhattan metric, with 7neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 66.49214659685863% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.61
[0.65098039 0.59215686 0.58661417]


manhattan metric, with 13neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 60.73298429319372% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.61
[0.62352941 0.59215686 0.62598425]


cosine metric, with 3neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 70.15706806282722% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.69
[0.70588235 0.6627451  0.70866142]


cosine metric, with 7neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 70.68062827225131% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.70
[0.68235294 0.6745098  0.74015748]


cosine metric, with 13neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 69.63350785340315% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.71
[0.69411765 0.69019608 0.73622047]


chebyshev metric, with 3neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 51.832460732984295% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.53
[0.51372549 0.51372549 0.5511811 ]


chebyshev metric, with 7neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 49.21465968586388% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.52
[0.54509804 0.51764706 0.50787402]


chebyshev metric, with 13neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 50.78534031413613% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.52
[0.54509804 0.50588235 0.51181102]


euclidean metric, with 3neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 63.87434554973822% 
Cross Validation Accuracy: 0.60
[0.61568627 0.59215686 0.59055118]




/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


euclidean metric, with 7neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 65.96858638743456% 
Cross Validation Accuracy: 0.62
[0.60784314 0.58823529 0.67716535]




/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


euclidean metric, with 13neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 59.68586387434554% 
Cross Validation Accuracy: 0.62
[0.58039216 0.62745098 0.64566929]




/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


manhattan metric, with 3neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 62.30366492146597% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.60
[0.61176471 0.59607843 0.59055118]


manhattan metric, with 7neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 67.5392670157068% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.62
[0.65882353 0.6        0.61417323]


manhattan metric, with 13neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 67.01570680628272% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.62
[0.62352941 0.60784314 0.62598425]


cosine metric, with 3neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 70.15706806282722% 
Cross Validation Accuracy: 0.69
[0.70588235 0.6627451  0.70472441]




/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


cosine metric, with 7neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 70.15706806282722% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.71
[0.68627451 0.69411765 0.73622047]


cosine metric, with 13neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 69.10994764397905% 
Cross Validation Accuracy: 0.71
[0.69411765 0.69803922 0.73622047]




/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


chebyshev metric, with 3neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 51.832460732984295% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.52
[0.51764706 0.51372549 0.54330709]


chebyshev metric, with 7neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 50.26178010471204% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.52
[0.54509804 0.52156863 0.50787402]


chebyshev metric, with 13neighbors and distance weighted for Bag of words : 
KNN with BOW accuracy = 52.35602094240838% 


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.53
[0.54901961 0.52156863 0.51181102]


euclidean metric, with 3neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.15706806282722%
Cross Validation Accuracy: 0.71
[0.6745098  0.76078431 0.70472441]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


euclidean metric, with 7neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.68062827225131%
Cross Validation Accuracy: 0.73
[0.71372549 0.7372549  0.74015748]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


euclidean metric, with 13neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 71.20418848167539%
Cross Validation Accuracy: 0.74
[0.74509804 0.72941176 0.74015748]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


manhattan metric, with 3neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 64.3979057591623%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.64
[0.60784314 0.6627451  0.64173228]
manhattan metric, with 7neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 67.01570680628272%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.60
[0.63921569 0.56470588 0.6023622 ]
manhattan metric, with 13neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 60.20942408376963%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.58
[0.57647059 0.5372549  0.62992126]
cosine metric, with 3neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.68062827225131%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.73
[0.72941176 0.76470588 0.70472441]
cosine metric, with 7neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.15706806282722%
Cross Validation Accuracy: 0.74
[0.70196078 0.73333333 0.79527559]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


cosine metric, with 13neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 71.72774869109948%
Cross Validation Accuracy: 0.76
[0.76470588 0.72941176 0.79527559]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


chebyshev metric, with 3neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 57.06806282722513%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.55
[0.54901961 0.52941176 0.57874016]
chebyshev metric, with 7neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 58.1151832460733%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.56
[0.58039216 0.52156863 0.57086614]
chebyshev metric, with 13neighbors and uniform weighted for TF-IDF : 
KNN with TFIDF accuracy = 53.92670157068062%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.54
[0.5372549  0.54117647 0.54724409]
euclidean metric, with 3neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.15706806282722%
Cross Validation Accuracy: 0.71
[0.6745098  0.76078431 0.70472441]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


euclidean metric, with 7neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.68062827225131%
Cross Validation Accuracy: 0.74
[0.71764706 0.74901961 0.74015748]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


euclidean metric, with 13neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 71.20418848167539%
Cross Validation Accuracy: 0.74
[0.74509804 0.73333333 0.73622047]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


manhattan metric, with 3neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 64.92146596858639%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.64
[0.61176471 0.66666667 0.64173228]
manhattan metric, with 7neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 68.06282722513089%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.61
[0.63921569 0.58823529 0.60629921]
manhattan metric, with 13neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 64.3979057591623%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.60
[0.58823529 0.56470588 0.63779528]
cosine metric, with 3neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.68062827225131%
Cross Validation Accuracy: 0.73
[0.72941176 0.76470588 0.69685039]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


cosine metric, with 7neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 70.15706806282722%
Cross Validation Accuracy: 0.75
[0.70588235 0.74901961 0.79133858]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


cosine metric, with 13neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 71.20418848167539%
Cross Validation Accuracy: 0.76
[0.76078431 0.74117647 0.78346457]


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


chebyshev metric, with 3neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 57.06806282722513%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.55
[0.54901961 0.52941176 0.57086614]
chebyshev metric, with 7neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 58.1151832460733%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.56
[0.58431373 0.5254902  0.56692913]
chebyshev metric, with 13neighbors and distance weighted for TF-IDF : 
KNN with TFIDF accuracy = 53.92670157068062%


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(


Cross Validation Accuracy: 0.55
[0.54509804 0.54901961 0.54330709]


# Section 4: SPAM TEXT DATASET
Now let's use what we've learnt to classify texts as spam or not spam.

In [ ]:
# Upload the spam text data CSV file that has been shared with you. You can also download the file from https://www.kaggle.com/datasets/uciml/sms-spam-collection-dataset
# Run this cell, click on the 'Choose files' button and upload the file.
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [ ]:
import pandas as pd
df = pd.read_csv('spam.csv', error_bad_lines=False)
df

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df['Category'] = df['Category'].map({'ham': 0, 'spam': 1})

In [ ]:
df.head(5)

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
len(df)

5572

In [ ]:
from sklearn import metrics, neighbors
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict

## TASK - 2: Tweak the models below and see results with different parameters and distance metrics.

def bow_knn(metric_type,no_of_neighbors,weight):
    """Method for determining nearest neighbors using bag-of-words and K-Nearest Neighbor algorithm"""

    training_data = pd.read_csv('spam.csv')
    training_data['Category'] = training_data['Category'].map({'ham': 0, 'spam': 1})
    X_train, X_test, y_train, y_test = train_test_split(training_data["Message"], training_data["Category"], test_size=0.2, random_state=5)
    X_train, X_test = createBagOfWords(X_train, X_test, remove_stopwords=True, lemmatize=True, stemmer=False)
    knn = neighbors.KNeighborsClassifier(n_neighbors=no_of_neighbors, weights=weight, algorithm='auto', leaf_size=30, p=2, metric=metric_type, metric_params=None, n_jobs=1)

    knn.fit(X_train, y_train)
    predicted = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, predicted)
    print(str(metric_type)+' metric, with '+str(no_of_neighbors)+'neighbors and '+str(weight)+' weighted for Bag of words : ')
    print('KNN with BOW accuracy = ' + str(acc * 100) + '%')

    scores = cross_val_score(knn, X_train, y_train, cv=3)
    print("Cross Validation Accuracy: %0.2f" % (scores.mean()))
    print(scores)
    print('\n')
    return predicted, y_test


def tfidf_knn(metric_type,no_of_neighbors,weight):
    """Method for determining nearest neighbors using tf-idf and K-Nearest Neighbor algorithm"""

    training_data = pd.read_csv('spam.csv')
    training_data['Category'] = training_data['Category'].map({'ham': 0, 'spam': 1})
    X_train, X_test, y_train, y_test = train_test_split(training_data["Message"], training_data["Category"], test_size=0.2, random_state=5)
    X_train, X_test = createTFIDF(X_train, X_test, remove_stopwords=True, lemmatize=True, stemmer=False)
    knn = neighbors.KNeighborsClassifier(n_neighbors=no_of_neighbors, weights=weight, algorithm='brute', leaf_size=30, p=2, metric=metric_type, metric_params=None, n_jobs=1)

    knn.fit(X_train, y_train)
    predicted = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, predicted)
    print(str(metric_type)+' metric, with '+str(no_of_neighbors)+'neighbors and '+str(weight)+' weighted for TF-IDF : ')
    print('KNN with TFIDF accuracy = ' + str(acc * 100) + '%')

    scores = cross_val_score(knn, X_train, y_train, cv=3)
    print("Cross Validation Accuracy: %0.2f" % (scores.mean()))
    print(scores)
    print('\n')
    return predicted, y_test

In [ ]:
#We iterate the algorith for different metrics,no of neighbors and weights type
# This cell may take some time to run
#Bag of words
metrics_list=['euclidean','manhattan','cosine','chebyshev']
neighbors_list=[7,13]
weight_type=['uniform','distance']
for weight in weight_type:
  for metric_type in metrics_list:
    for no_of_neighbors in neighbors_list:
      predicted,y_test=bow_knn(metric_type,no_of_neighbors,weight)  

#TF-IDF
for weight in weight_type:
  for metric_type in metrics_list:
    for no_of_neighbors in neighbors_list:
      predicted,y_test=tfidf_knn(metric_type,no_of_neighbors,weight)  



euclidean metric, with 7neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 90.94170403587444%
Cross Validation Accuracy: 0.90
[0.89838493 0.8923284  0.9037037 ]


euclidean metric, with 13neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 88.87892376681614%
Cross Validation Accuracy: 0.88
[0.88559892 0.87617766 0.88350168]


manhattan metric, with 7neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 90.49327354260089%
Cross Validation Accuracy: 0.89
[0.89569314 0.8909825  0.89090909]


manhattan metric, with 13neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 88.60986547085203%
Cross Validation Accuracy: 0.88
[0.8781965  0.87550471 0.88080808]


cosine metric, with 7neighbors and uniform weighted for Bag of words : 
KNN with BOW accuracy = 97.57847533632287%
Cross Validation Accuracy: 0.96
[0.95625841 0.96231494 0.96228956]


cosine metric, with 13neighbors and uniform weighted for Bag of wo

### Questions to Think About and Answer
1. Why does the TF-IDF approach generally result in a better accuracy than Bag-of-Words ?
2. Can you think of techniques that are better than both BoW and TF-IDF ?
3. Read about Stemming and Lemmatization from the resources given below. Think about the pros/cons of each.

**1ans**:TF-IDF results in a better accuracy than Bag-of-Words,because it eliminates all the possible stopwords from text and considers only the Keywords significant in Documents.since,BOW depends on frequency of words,it might consider stopwords,thus giving lower accuracy in Text Classification.

**2ans**:Word2vec method is a technique which is better than both BOW and TF-IDF,because it considers the context of a word rather than it's frequency.It classifies a word based on it's synonym,gender etc.So,it gives better accuracy than both BOW and TF-IDF.

**3ans:** **Stemming**

**Pros:**Gives the Base of a word,thus decreasing the word length and making it fast to run

**Cons:**Most of the times,gives an inaccurate and meaningless words in the output.

**Lemmatization:**

**Pros**:Compared to skemming,gives accurate and dictionary words as the output.

**Cons:**Harder to Implement and is slower compared to skemming.

Hence,Lemmatization gives better accuracy than Skemming.





### Useful Resources for further reading
1. Stemming and Lemmatization: https://nlp.stanford.edu/IR-book/html/htmledition/stemming-and-lemmatization-1.html
2. TF-IDF and BoW : https://www.analyticsvidhya.com/blog/2020/02/quick-introduction-bag-of-words-bow-tf-idf/
3. TF-IDF: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html
